spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties.hibernate-dialect: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: update


  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
